openapi: 3.0.0
info:
  title: Insurance App API
  description: Insurance App API
  version: 1.0.0
paths:
  /user:
    post:
      tags:
        - user
      summary: Create new user in system with defined amount of many in PLN
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'

  /accounts/{accountNumber}/exchange:
    post:
      tags:
        - exchange
      summary: Exchange money
      operationId: exchangeMoney
      parameters:
        - name: accountNumber
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Currency code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExchangeMoneyRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeMoneyResponse'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /cantor/exchange:
    post:
      tags:
        - exchange
      summary: Exchange
      operationId: exchange
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExchangeRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeResponse'

components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        firstname:
          type: string
        surname:
          type: string
        amount:
          type: number

    CreateUserResponse:
      type: object
      properties:
        accountNumber:
          type: string
          format: uuid

    ExchangeMoneyRequest:
      type: object
      properties:
        sourceCurrencyCode:
          type: string
        targetCurrencyCode:
          type: string
        amount:
          type: number

    ExchangeMoneyResponse:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        sourceCurrencyCode:
          type: string
        targetCurrencyCode:
          type: string
        amount:
          type: number

    ExchangeRequest:
      type: object
      properties:
        sourceCurrencyCode:
          type: string
        targetCurrencyCode:
          type: string
        amount:
          type: number

    ExchangeResponse:
      type: object
      properties:
        sourceCurrencyCode:
          type: string
        targetCurrencyCode:
          type: string
        sourceAmount:
          type: number
        targetAmount:
          type: number

    Error:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
