openapi: 3.0.0
info:
  title: Open Tip Planner API
  description: Open Tip Planner API
  version: 1.0.0
paths:
  /exchangerates/rates/c/{currency_code}/:
    get:
      tags:
        - exchangerates
      summary: Return exchange rates
      operationId: exchangeRates
      parameters:
        - name: currency_code
          in: path
          required: true
          schema:
            type: string
          description: Currency code
        - name: format
          in: query
          required: false
          schema:
            type: string
            default: json
            description: Format of returned response
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NbpExchangeResponse'

  /exchangerates/rates/c/{currency_code}/{exchange_date}/:
    get:
      tags:
        - exchangerates
      summary: Return exchange rates for indicated day in format (yyyy-MM-dd)
      operationId: exchangeRatesByDay
      parameters:
        - name: currency_code
          in: path
          required: true
          schema:
            type: string
          description: Currency code
        - name: exchange_date
          in: path
          required: true
          schema:
            type: string
            format: date
          description: Date in format yyyy-MM-dd
        - name: format
          in: query
          required: false
          schema:
            type: string
            default: json
            description: Format of returned response
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NbpExchangeResponse'

components:
  schemas:
    NbpExchangeResponse:
      type: object
      properties:
        table:
          type: string
        currency:
          type: string
        code:
          type: string
        rates:
          type: array
          items:
            $ref: '#/components/schemas/NbpExchangeRates'

    NbpExchangeRates:
      type: object
      properties:
        "no":
          type: string
        effectiveDate:
          type: string
          format: date
        bid:
          type: number
        ask:
          type: number
