### Create new user account with init amount of many in PLN currecy
POST http://localhost:8080/api/v1/users
Accept: application/json
Content-Type: application/json

{
  "firstname": "Jan",
  "surname": "Kowalski",
  "amount": 1500.00
}

### Exchange money form PLN -> USD
POST http://localhost:8080/api/v1/accounts/{account_id}/exchange
Accept: application/json
Content-Type: application/json

{
  "sourceCurrencyCode": "PLN",
  "targetCurrencyCode": "USD",
  "amount": 10.00
}

### Returns account details
GET http://localhost:8080/api/v1/accounts/{account_id}
Accept: application/json
Content-Type: application/json
